sync_moderation_state_translations: true

content_translation_revision.settings:
  type: config_object
  label: 'CTR settings'
  mapping:
    sync_moderation_state_translations:
      type: boolean
      label: 'Sync translations'
